name: CRUD SQL File Operations

on:
  workflow_dispatch: # Manually trigger the workflow from the Actions tab

jobs:
  sql_crud_job:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository to work with local files
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install requests

    # CREATE SQL file
    - name: Set Create Action
      run: |
        echo "create" > action.txt
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        ACTION: 'create'

    # READ SQL file
    - name: Set Read Action
      run: |
        echo "read" > action.txt
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        ACTION: 'read'

    # UPDATE SQL file
    - name: Set Update Action
      run: |
        echo "update" > action.txt
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        ACTION: 'update'

    # DELETE SQL file
    - name: Set Delete Action
      run: |
        echo "delete" > action.txt
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        ACTION: 'delete'

    # Run CRUD Operations
    - name: Run CRUD Operations
      run: |
        python crud_sql_operations.py
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        ACTION: $(cat action.txt)

    # Commit the changes if needed
    - name: Commit changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add database.sql || echo "No changes to database.sql"
        git commit -m "CRUD operation on database.sql" || echo "No changes to commit"

    # Push the changes back to the repository
    - name: Push changes
      run: |
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
